print("Enter two numbers to perform arithmetic operations:", end = " ")
a, b = map(int, input().split())
print("Arithmetic operations performed on the given numbers are as follows:")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulo operation result:", a % b)
print("Exponentiation:", a ** b)